name: dinov3
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - aom=3.9.1=he0c23c2_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - blosc=1.21.6=hfd34d9b_1
  - brotli-python=1.2.0=py311h69b5583_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-blosc2=2.22.0=h3cf07e4_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpuonly=2.0=0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=8.0.0=gpl_h70aa942_905
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.44.4=h1f5b9c4_0
  - giflib=5.2.2=h64bf75a_0
  - glslang=15.4.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf5=1.14.6=nompi_h89f0904_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.11.11=py311haf4ede9_0
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.2=h1608b31_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.3.0=h57928b3_641
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jxrlib=1.1=hcfcfb64_3
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libasprintf=0.22.5=h5728263_3
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang13=21.1.7=default_ha2db4b5_1
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgettextpo=0.22.5=h5728263_3
  - libglib=2.86.2=hd9c3897_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - liblapack=3.9.0=13_h018ca30_netlib
  - liblapacke=3.9.0=13_h0d55cca_netlib
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libopencv=4.12.0=qt6_py311hf6c31d6_607
  - libopenvino=2025.2.0=hbf28c98_1
  - libopenvino-auto-batch-plugin=2025.2.0=hdd9a157_1
  - libopenvino-auto-plugin=2025.2.0=hdd9a157_1
  - libopenvino-hetero-plugin=2025.2.0=hc39e7c6_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hbf28c98_1
  - libopenvino-ir-frontend=2025.2.0=hc39e7c6_1
  - libopenvino-onnx-frontend=2025.2.0=hee3bb10_1
  - libopenvino-paddle-frontend=2025.2.0=hee3bb10_1
  - libopenvino-pytorch-frontend=2025.2.0=hac47afa_1
  - libopenvino-tensorflow-frontend=2025.2.0=h293fe96_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hac47afa_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - librsvg=2.58.4=h5ce5fed_3
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libusb=1.0.29=h1839187_0
  - libuv=1.51.0=hfd05255_1
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - lz4-c=1.10.0=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2023.1.0=h6a75c08_48682
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.5=py311h80b3fa1_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - opencv=4.12.0=qt6_py311h19c12f8_607
  - openexr=3.4.4=ha75af49_0
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.4=h24db6dd_0
  - openjph=0.25.3=hf13a347_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pango=1.56.4=h03d888a_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=10.4.0=py311h5592be9_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311hf893f09_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pugixml=1.15=h372dad0_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py311hf16eb4e_607
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py311h17033d2_2
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qt6-main=6.9.3=ha0de62e_1
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-image=0.25.2=py311h11fd7f3_2
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.28=h5112557_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.3=haa9a63f_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - spirv-tools=2025.4=h49e36cd_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2021.13.0=hd094cb3_4
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_3
  - torchaudio=2.5.1=py311_cpu
  - torchvision=0.20.1=py311_cpu
  - tornado=6.5.2=py311h3485c13_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zfp=1.0.1=h2f0f97f_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_1
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - dinov3==0.0.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - matplotlib==3.10.7
      - omegaconf==2.3.0
      - pyparsing==3.2.5
      - regex==2025.11.3
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - segment-anything==1.0
      - submitit==1.5.3
      - sympy==1.13.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
prefix: C:\Users\phili\anaconda3\envs\dinov3
